### ISSUE TITLE
error http 500

### ISSUE THREAD

**Issue by hammer4u** [ColorlibHQ/fashe-wp#14]
Hi,
I installed this theme and the site is no longer working and show me this error 
nextshoes.ro is currently unable to handle this request.
HTTP ERROR 500

anybody can help me pls?
Thank you

**Comment by cristianraiber** [comment]
@hammer4u - You sure you weren't looking for this: https://github.com/ColorlibHQ/Fashe ?

**Comment by hammer4u** [comment]
@cristianraiber No,i use Wordpress, she was installed correctly and when I activate it I give the error 500

i updated WordPress to 4.9.8 and i have the same problem

**Comment by cristianraiber** [comment]
Do you also have this installed: https://github.com/ColorlibHQ/fashe-companion? 

Also, downloading from GitHub directly doesn't really work :) There are two GitHub sub-modules that can only be obtained with git clone and/or when this theme is actually released publicly.

**Comment by hammer4u** [comment]
@cristianraiber  Yes i also installed
i check error.logs and give me this errors

[11-Oct-2018 17:11:00 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.
[11-Oct-2018 17:11:00 UTC] The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data.
[11-Oct-2018 17:11:00 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.
[11-Oct-2018 17:11:00 UTC] The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data.
[11-Oct-2018 17:11:00 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.
[11-Oct-2018 17:11:00 UTC] The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data.
[11-Oct-2018 17:11:00 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.
[11-Oct-2018 17:11:00 UTC] The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data.
[11-Oct-2018 17:11:00 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.
[11-Oct-2018 17:11:00 UTC] The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data.
[11-Oct-2018 17:12:10 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.
[11-Oct-2018 17:12:10 UTC] The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data.
[11-Oct-2018 17:12:10 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.
[11-Oct-2018 17:12:10 UTC] The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data.
[11-Oct-2018 17:12:10 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.
[11-Oct-2018 17:12:10 UTC] The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data.
[11-Oct-2018 17:12:10 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.
[11-Oct-2018 17:12:10 UTC] The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data.
[11-Oct-2018 17:12:10 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.
[11-Oct-2018 17:12:10 UTC] The WC_Cart::get_item_data function is deprecated since version 3.3. Replace with wc_get_formatted_cart_item_data.
[11-Oct-2018 17:13:49 UTC] PHP Fatal error:  Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found in /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php:172
Stack trace:
#0 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php(67): Epsilon_init_Dashboard->init_nav_menus()
#1 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php(82): Epsilon_init_Dashboard->__construct(Object(WP_Theme))
#2 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/classes/Class-Config.php(56): Epsilon_init_Dashboard::get_instance()
#3 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/classes/Class-Config.php(41): Fashe->init()
#4 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/functions.php(109): Fashe->__construct()
#5 /home/u232722263/public_html/wp-settings.php(426): include('/home/u23272226...')
#6 /home/u232722263/public_html/wp-config.php(103): require_once('/home/u23272226.. in /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php on line 172
[11-Oct-2018 17:13:51 UTC] PHP Fatal error:  Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found in /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php:172
Stack trace:
#0 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php(67): Epsilon_init_Dashboard->init_nav_menus()
#1 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php(82): Epsilon_init_Dashboard->__construct(Object(WP_Theme))
#2 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/classes/Class-Config.php(56): Epsilon_init_Dashboard::get_instance()
#3 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/classes/Class-Config.php(41): Fashe->init()
#4 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/functions.php(109): Fashe->__construct()
#5 /home/u232722263/public_html/wp-settings.php(426): include('/home/u23272226...')
#6 /home/u232722263/public_html/wp-config.php(103): require_once('/home/u23272226.. in /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php on line 172
[11-Oct-2018 17:13:52 UTC] PHP Fatal error:  Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found in /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php:172
Stack trace:
#0 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php(67): Epsilon_init_Dashboard->init_nav_menus()
#1 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php(82): Epsilon_init_Dashboard->__construct(Object(WP_Theme))
#2 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/classes/Class-Config.php(56): Epsilon_init_Dashboard::get_instance()
#3 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/classes/Class-Config.php(41): Fashe->init()
#4 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/functions.php(109): Fashe->__construct()
#5 /home/u232722263/public_html/wp-settings.php(426): include('/home/u23272226...')
#6 /home/u232722263/public_html/wp-config.php(103): require_once('/home/u23272226.. in /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php on line 172
[11-Oct-2018 17:14:02 UTC] PHP Fatal error:  Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found in /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php:172
Stack trace:
#0 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php(67): Epsilon_init_Dashboard->init_nav_menus()
#1 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php(82): Epsilon_init_Dashboard->__construct(Object(WP_Theme))
#2 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/classes/Class-Config.php(56): Epsilon_init_Dashboard::get_instance()
#3 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/classes/Class-Config.php(41): Fashe->init()
#4 /home/u232722263/public_html/wp-content/themes/fashe-wp-master/functions.php(109): Fashe->__construct()
#5 /home/u232722263/public_html/wp-settings.php(426): include('/home/u23272226...')
#6 /home/u232722263/public_html/wp-config.php(103): require_once('/home/u23272226.. in /home/u232722263/public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php on line 172
[11-Oct-2018 17:14:26 UTC] PHP Fatal error:  Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found in /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php:172
Stack trace:
#0 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php(67): Epsilon_init_Dashboard->init_nav_menus()
#1 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php(82): Epsilon_init_Dashboard->__construct(Object(WP_Theme))
#2 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/classes/Class-Config.php(56): Epsilon_init_Dashboard::get_instance()
#3 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/classes/Class-Config.php(41): Fashe->init()
#4 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/functions.php(109): Fashe->__construct()
#5 /home/u232722263/public_html/wp-settings.php(426): include('/home/u23272226...')
#6 /home/u232722263/public_html/wp-config.php(103): require_once('/home/u2327 in /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php on line 172
[11-Oct-2018 17:18:47 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:18:47 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:18:47 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:18:47 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:19:43 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:19:43 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:19:43 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:19:43 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:19:55 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:19:55 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:19:55 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[11-Oct-2018 17:19:55 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:38:03 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:38:03 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:38:03 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:38:03 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:39:02 UTC] PHP Fatal error:  Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found in /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php:172
Stack trace:
#0 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php(67): Epsilon_init_Dashboard->init_nav_menus()
#1 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php(82): Epsilon_init_Dashboard->__construct(Object(WP_Theme))
#2 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/classes/Class-Config.php(56): Epsilon_init_Dashboard::get_instance()
#3 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/classes/Class-Config.php(41): Fashe->init()
#4 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/functions.php(109): Fashe->__construct()
#5 /home/u232722263/public_html/wp-settings.php(426): include('/home/u23272226...')
#6 /home/u232722263/public_html/wp-config.php(103): require_once('/home/u2327 in /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php on line 172
[12-Oct-2018 11:39:16 UTC] PHP Fatal error:  Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found in /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php:172
Stack trace:
#0 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php(67): Epsilon_init_Dashboard->init_nav_menus()
#1 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php(82): Epsilon_init_Dashboard->__construct(Object(WP_Theme))
#2 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/classes/Class-Config.php(56): Epsilon_init_Dashboard::get_instance()
#3 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/classes/Class-Config.php(41): Fashe->init()
#4 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/functions.php(109): Fashe->__construct()
#5 /home/u232722263/public_html/wp-settings.php(426): include('/home/u23272226...')
#6 /home/u232722263/public_html/wp-config.php(103): require_once('/home/u2327 in /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php on line 172
[12-Oct-2018 11:39:20 UTC] PHP Fatal error:  Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found in /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php:172
Stack trace:
#0 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php(67): Epsilon_init_Dashboard->init_nav_menus()
#1 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php(82): Epsilon_init_Dashboard->__construct(Object(WP_Theme))
#2 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/classes/Class-Config.php(56): Epsilon_init_Dashboard::get_instance()
#3 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/classes/Class-Config.php(41): Fashe->init()
#4 /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/functions.php(109): Fashe->__construct()
#5 /home/u232722263/public_html/wp-settings.php(426): include('/home/u23272226...')
#6 /home/u232722263/public_html/wp-config.php(103): require_once('/home/u2327 in /home/u232722263/public_html/wp-content/themes/fashe-wp-master1/inc/class-epsilon-init-dashboard.php on line 172
[12-Oct-2018 11:40:46 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:40:46 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:40:46 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:40:46 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:45:07 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:45:07 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "read_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:45:07 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161
[12-Oct-2018 11:45:07 UTC] PHP Notice:  map_meta_cap a fost denumit <strong>incorect</strong>. Tipul de articol shop_order nu este înregistrat, așadar s-ar putea să nu fie sigură verificarea capabilității "edit_post" pentru articole de acel tip. Te rog vezi <a href="https://codex.wordpress.org/Debugging_in_WordPress">Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 4.4.0.) in /home/u232722263/public_html/wp-includes/functions.php on line 4161

**Comment by codepixar** [comment]
@cristianraiber - There has no WooCommerce deprecated function in the fashe-wp theme. I'm trying to find out error but i don't find any thing.

**Comment by cristianraiber** [comment]
@hammer4u - which PHP version are you using? We're trying to replicate this at our end but with no success.

**Comment by hammer4u** [comment]
@cristianraiber when i access phpmyadmin write this Version information: 4.7.9
thanks

**Comment by hammer4u** [comment]
I installed wordpress 4.9.8 on localhost ... i try to install theme and it gives me the same error

**Comment by cristianraiber** [comment]
@hammer4u - please go into your `wp-config.php` file and set `WP_DEBUG` to `false`. 

These are not errors but notices. The theme should work fine IF you disable WP_DEBUG while we investigate this issue further. Right now, I've got no clue why this is happening at your end as I've tried reproducing it on both Windows & Mac and not once did it happen.

**Comment by cristianraiber** [comment]
Closing this due to inactivity from @hammer4u
